"""Sound Addition rule (제29-30항).

Handles:
1. ㄴ-insertion (제29항): Inserts 'ㄴ' at compound/derived word boundaries before '이', '야', '여', '요', '유'
   (솜이불 -> [솜니불], 서울역 -> [서울력], 물약 -> [물략]).
2. Saisiot branching (제30항 1): Branches into dropping the saisiot vs keeping it as [ㄷ]
   (냇가 -> [내까, 낻까], 깃발 -> [기빨, 긷빨]).
"""

from typing import List, Set
from korean_pronunciation.state import PronunciationState, Syllable
from korean_pronunciation.rules.base import BaseRule
from korean_pronunciation.jamo_constants import FORTITION_MAP

# Common compound words with written saisiot (사이시옷)
SAISIOT_WORDS = {
    "냇가", "깃발", "콧등", "뱃머리", "촛불", "뱃사공", "댓잎", "냇물", "빗물", "뒷일", 
    "나뭇잎", "깻잎", "베갯잇", "바닷가", "뱃길", "핏줄", "햇볕", "귓병"
}

# Common words that undergo ㄴ-addition
N_ADDITION_WORDS = {
    "솜이불", "홑이불", "막일", "서울역", "물약", "알약", "들일", "깻잎", "나뭇잎", 
    "베갯잇", "색연필", "식용유", "영업용", "국민윤리", "담요", "눈요기", "한일", "옷입다"
}


class SoundAdditionRule(BaseRule):
    """Applies Sound Addition rules (ㄴ-첨가, 사이시옷) per articles 29 and 30."""

    @property
    def name(self) -> str:
        return "SoundAddition"

    @property
    def article(self) -> str:
        return "제29-30항"

    def apply(self, state: PronunciationState) -> List[PronunciationState]:
        new_syllables = list(state.syllables)
        n = len(new_syllables)
        
        # We will collect all branches generated by this rule.
        current_branches = [new_syllables]
        changed = False
        
        def is_word_boundary_match(branch: List[Syllable], idx: int, word_list: Set[str]) -> bool:
            orig_text = "".join(s.original for s in branch)
            char_idx = 0
            for s_i in range(idx):
                char_idx += len(branch[s_i].original)
            
            for w in word_list:
                start = 0
                while True:
                    start_pos = orig_text.find(w, start)
                    if start_pos == -1:
                        break
                    boundary_char_pos = char_idx + len(branch[idx].original) - 1
                    if start_pos <= boundary_char_pos < start_pos + len(w) - 1:
                        return True
                    start = start_pos + 1
            return False

        i = 0
        while i < n - 1:
            # We process each branch
            next_branches: List[List[Syllable]] = []
            
            for branch in current_branches:
                curr_syl = branch[i]
                next_syl = branch[i + 1]
                
                # --- Rule 29: ㄴ-Insertion ---
                # Preceding ends in consonant, following starts with '이, 야, 여, 요, 유' (ㅇ onset)
                # Must be a boundary: either flagged by analyzer (has_boundary_before) or separated by space.
                
                is_y_vowel = next_syl.is_hangul and next_syl.jungseong in ("ㅣ", "ㅑ", "ㅕ", "ㅛ", "ㅠ")
                
                # Case A: Adjacent syllables (e.g. 솜이불, 서울역)
                if (curr_syl.is_hangul and curr_syl.jongseong and 
                        next_syl.is_hangul and next_syl.choseong == "ㅇ" and is_y_vowel):
                    
                    is_inflectional = next_syl.is_grammatical
                    is_n_addition_word = is_word_boundary_match(branch, i, N_ADDITION_WORDS)
                    is_boundary = (next_syl.has_boundary_before and not is_inflectional) or is_n_addition_word
                    
                    if is_boundary:
                        copied_branch = list(branch)
                        copied_branch[i + 1] = next_syl.copy(choseong="ㄴ")
                        next_branches.append(copied_branch)
                        changed = True
                        continue
                    
                # Case B: Across a space (e.g. 한 일, 옷 입다)
                elif (curr_syl.is_hangul and curr_syl.jongseong and
                      not next_syl.is_hangul and next_syl.original == " " and
                      i + 2 < n and branch[i + 2].is_hangul and 
                      branch[i + 2].choseong == "ㅇ" and 
                      branch[i + 2].jungseong in ("ㅣ", "ㅑ", "ㅕ", "요", "ㅠ")):
                    
                    target_syl = branch[i + 2]
                    # Branch 1: Keep original (no ㄴ-addition)
                    branch_a = list(branch)
                    # Branch 2: Add ㄴ
                    branch_b = list(branch)
                    branch_b[i + 2] = target_syl.copy(choseong="ㄴ")
                    next_branches.extend([branch_a, branch_b])
                    changed = True
                    continue

                # --- Rule 30.1: Saisiot Branching ---
                # Saisiot ends in 'ㅅ', followed by 'ㄱ, ㄷ, ㅂ, ㅅ, ㅈ'
                elif (curr_syl.is_hangul and curr_syl.jongseong == "ㅅ" and
                      next_syl.is_hangul and next_syl.choseong in FORTITION_MAP and
                      is_word_boundary_match(branch, i, SAISIOT_WORDS)):
                    
                    tense_onset = FORTITION_MAP[next_syl.choseong]
                    
                    # Branch 1 (원칙): Drop 'ㅅ' and tensify next consonant
                    branch_a = list(branch)
                    branch_a[i] = curr_syl.copy(jongseong="")
                    branch_a[i + 1] = next_syl.copy(choseong=tense_onset)
                    
                    # Branch 2 (허용): Keep 'ㅅ' (will neutralize to [ㄷ] and tensify next consonant)
                    branch_b = list(branch)
                    branch_b[i + 1] = next_syl.copy(choseong=tense_onset)
                    
                    next_branches.extend([branch_a, branch_b])
                    changed = True
                    continue
                
                # No changes at this index for this branch
                next_branches.append(branch)
                
            current_branches = next_branches
            i += 1

        if changed:
            # Convert branches back to PronunciationState objects and deduplicate
            seen: Set[str] = set()
            states: List[PronunciationState] = []
            for b in current_branches:
                st = PronunciationState(syllables=tuple(b), applied_rules=state.applied_rules + (self.name,))
                key = st.canonical_key()
                if key not in seen:
                    seen.add(key)
                    states.append(st)
            return states
            
        return [state]
